#!/bin/sh

# cd to the directory we're run from
cd `dirname $0`

die() {
    echo "$@"
    exit 1
}

[ $0 = "/bin/sh" -o $0 = "/bin/bash" ] && die "cannot source the autochk script"

devel_cfg=./config

toplevel=$(git rev-parse --show-toplevel)

[ -d "$toplevel" ] || { pwd -P; die "not within a repository to get version info from"; }

#
# test absolute requirements for building with submodules checked out...
#
[ -d packaging/. -a -d bitrock-stack/. -a -s bitrock-stack/install-var-subst.sh ] ||
(
    cd $toplevel;
    [ -s $toplevel/.gitmodules ] || die "ERROR: no $toplevel/.gitmodules file was found but symlinks are broken."
    git submodule deinit -f .
    rm -rf 000-external   # to be certain nothing is checked out now...
    git submodule | while read i j k; do git checkout -f $j >/dev/null 2>/dev/null; done
)

git config --blob HEAD:.gitmodules --get-regex submodule'.*.branch'  |
while read mod branch; do
    mod=${mod#submodule.}; mod=${mod%.branch}; branch=${branch##*/}
    echo module:$mod '-->' branch:$branch
    # clean out old tracking branches!
    git --git-dir=$toplevel/.git/modules/$mod branch -D $branch 2>/dev/null
    git --git-dir=$toplevel/.git/modules/$mod fetch origin +refs/heads/$branch:refs/remotes/origin/$branch
done

git submodule update --init --remote --rebase || die "update failed"
git submodule foreach -q 'git rebase --abort 2>/dev/null || exit 0; exit -1;' || die "failed to update correctly"
git submodule foreach -q 'name1=$(git name-rev HEAD); name2=$(git describe --tags HEAD 2>/dev/null || git describe --all HEAD) ; echo "$path ---> $name1 / $name2"'

[ -L config/set_full_version ] || ln -sf ../packaging/common_z/set_zmanda_version config/set_full_version

[ -d config -a -d $devel_cfg/amanda -a -d $devel_cfg/macro-archive \
	-a -d $devel_cfg/gnulib -a -d $devel_cfg/gettext-macros ] || \
    die "ERROR: m4 include check failed"

[ -s config/set_full_version -a -L config/set_full_version ] || \
    die "ERROR: cannot use config/set_full_version symlink.  submodule checkout failed."

[ -s bitrock-stack/build-var-subst.sh ] || die "ERROR: cannot use bitrock-stack symlink.  submodule checkout failed."

set -- awk make gcc sed libtoolize \
        autoconf automake autoheader \
        swig perl bison flex gettext mailx \
        dump xinetd smbclient git tar cpio \
        strip ar base64 openssl mtx

failed=""
export PATH="$PATH:/bin:/usr/bin:/sbin:/usr/sbin"
for i do eval 'type $1 >/dev/null' $i || failed="$failed $i"; done

if [ -n "$failed" ]; then die "ERROR: failed executible tests: $failed"; fi

set -- CPAN List::Util IO::Socket::SSL Carp Data::Dumper ExtUtils::Embed 
for i do perl -e "use $i;" || failed="$failed $i"; done

if [ -n "$failed" ]; then die "ERROR: failed executible tests: $failed"; fi

exit 0
