#!/usr/bin/env bash

#
# VERSION: the identifier for the amanda determined from git
#	information.
# PKG_NAME_VER: the full version name of amanda we're working on.  This will
#	become part of the sun name.  {PKG_NAME_VER} gets substituted
#

buildtype=${1:-both}
shift

BUILDVER="4.0"
# set the var buildpkg_dir as well
. ./packaging/common/build_functions.sh
. ./packaging/common/set_zmanda_version

export PATH
export PKG_DIR=$(realpath .)
mach=`uname -m`

do_tar_package() {
    gen_pkg_build_config "$@"
    gen_top_environ
    do_top_package "${PKG_NAME_VER}"
}

set -e

case "$buildtype,$mach,$BUILDVER" in
   server,*,*)
        do_tar_package "$buildpkg_dir/server${BUILDVER}"
        ;;

   client,*,*) ;&
   both,*,*)
        do_tar_package "$buildpkg_dir/client${BUILDVER}"
        ;;

   *) echo "ERROR: cannot build combination of $buildtype-$mach-${BUILDVER:-3.6}" >&2; exit -1 ;;
esac

true
