#!/bin/bash

srcdir=$1

if test -d .svn && svn info . > conftemp.svn; then
    SVN_REV=`grep Revision: conftemp.svn|cut -d: -f 2|cut -c2-`
    SVN_URL=`grep URL: conftemp.svn|cut -d: -f 2-|cut -c2-`
    SVN_PATH=`grep URL: conftemp.svn|cut -d "/" -f 7-`
    SVN_TYPE=`echo ${SVN_PATH} |cut -d "/" -f 1`
    SVN_BRANCH=`echo "${SVN_PATH}"| cut -d "/" -f 2`
    url=`grep URL: conftemp.svn|cut -d: -f 2-|cut -c2-`
fi

if test -d .git; then
    GIT_SHA1=`git rev-parse HEAD | cut -c -8 `
fi

if test -f FULL_VERSION; then
    OLD_VERSION=`cat FULL_VERSION`
else if test -n "$srcdir" && -f $srcdir/FULL_VERSION; then
    OLD_VERSION=`cat FULL_VERSION`
fi
fi

if test -n "$srcdir"; then
    VERSION=`cat $srcdir/VERSION`
else
    VERSION=`cat VERSION`
fi

if test -n "$SVN_REV"; then
    if test "${SVN_TYPE}" = "branches"; then
        VERSION=${VERSION}.svn.${SVN_REV}
    else if test "${SVN_TYPE}" = "trunk"; then
        VERSION=${VERSION}.svn.${SVN_REV}
    else
        RC=`echo "${SVN_BRANCH}"| grep "rc"`
        if test -n "$RC"; then
	    VERSION=`echo "${SVN_BRANCH}"| sed 's/[^0-9]*// ; s/[_.]//g'`
	    VERSION=`echo ${VERSION}| sed 's/^\([0-9]\)\([0-9]\)\([0-9]\)/\1.\2.\3/'`
        fi
    fi
    fi

else if test -n "$GIT_SHA1"; then
    VERSION=${VERSION}".git."${GIT_SHA1}

else
    VERSION=$OLD_VERSION
fi
fi

    echo "$VERSION" > FULL_VERSION

