#!/bin/bash

buildtype=${1:-both}
shift

# set the var buildpkg_dir as well
. ./packaging/common/build_functions.sh

. ./packaging/common/set_zmanda_version

export PKG_DIR=$(realpath .)
mach=`uname -m`

do_rpm_package() {
    gen_pkg_build_config $buildpkg_dir
    # take the spec/spec.src files and make a tarfile
    gen_top_environ
    tar -czvf rpmbuild/SOURCES/${PKG_NAME_VER}.tar.gz po/stamp-po
    do_top_package "$@"
}

set -e

case "$buildtype" in
   both)
        do_rpm_package "amanda.spec" \
              --define "subpkg server"
        #
        do_rpm_package "amanda-client.spec" \
              --define "subpkg client"
        ;;

   server)
        do_rpm_package "amanda.spec" \
              --define "subpkg server"
        ;;

   client)
	do_rpm_package "amanda-client.spec" \
              --define "subpkg client"
        ;;

   *) echo "ERROR: cannot build combination of $buildtype-$mach" >&2; exit -1 ;;
esac

true
