#!/bin/bash
# We're assuming that you've copied packaging/* from the 
# amanda-extensions source tree to the amanda source tree.
# (buildbot dist tarballs will not contain packaging files!)

# Buildpkg script for producing RPM packages. (Does not require root access.)
# Buildpkg is designed to be used by both buildbot (to automate rpm production)
# and by J Random User (to build an rpm for kicks).
#
# VERSION: the identifier for the amanda determined from subversion
#	information.  
# PKG_NAME_VER: the full version name of amanda we're working on.  This will
#	become part of the rpm name.  
# PKG_TARBALL: the name of the tarball which contains the source code.  it must
#     unpack into a directory named PKG_NAME_VER. 
# PKG_DIR: Rpmbuild expects absolute paths, so we provide this var.  It also
#     allows you to build somewhere other than `pwd`.  You probably don't want
#     to use the system-wide location, as the script tries to blow these
#     directories away.
# 
# Other Hints:
# Not everyone will want to use the ./configure options we provide.  The
# easiest way to change them is by editing the .spec file.  This isn't so
# easy, unfortunately.  Look at the %build section, and the %define xxxx 
# statements immediately above it. good luck.

pkg_name=amanda
. packaging/common/build_functions.sh
. packaging/common/set_amanda_version

[ -f "PKG_REV" ] || echo "1" > PKG_REV

[ -f "./configure" ] || \
    { echo "./configure does not exist, please run ./autogen"; exit 1; }

gen_pkg_build_config $pkg_root

# take the spec/spec.src files and make a tarfile
gen_top_environ

do_top_package "amanda.spec"
