#!/bin/bash

DEFINES=

buildtype=${1:-both}
shift

# set the var buildpkg_dir as well
. ./packaging/common/build_functions.sh

. ./packaging/common/set_zmanda_version

BUILDVER=${BUILDVER:-4.0}
export PKG_DIR=$(realpath .)
mach=`uname -m`

do_rpm_package() {
    gen_pkg_build_config $buildpkg_dir
    # take the spec/spec.src files and make a tarfile
    gen_top_environ
    tar -czvf rpmbuild/SOURCES/${PKG_NAME_VER}.tar.gz po/stamp-po
    #
    #
    #
    do_top_package "$@"
}

set -e

case "$buildtype,$mach,$BUILDVER" in
   both,x86_64,*)
        do_rpm_package "amanda${BUILDVER}.spec" \
              "${DEFINES[@]}" \
              --define "subpkg server"
        #
        do_rpm_package "amanda-client${BUILDVER}.spec" \
              --define "subpkg client"
        ;;

   server,x86_64,*)
        do_rpm_package "amanda${BUILDVER}.spec" \
              "${DEFINES[@]}" \
              --define "subpkg server"
        ;;

   client,*,*) ;&  both,*,*)
	do_rpm_package "amanda-client${BUILDVER}.spec" \
              --define "subpkg client"
        ;;

   *) echo "ERROR: cannot build combination of $buildtype-$mach-${BUILDVER:-3.6}" >&2; exit -1 ;;
esac

true
