#!/bin/bash

# Buildpkg script for producing RPM packages. (Does not require root access.)
# Buildpkg is designed to be used by both buildbot (to automate rpm production)
# and by J Random User (to build an rpm for kicks).  The odd way of handling
# all optioins through environment variables is a product of buildbot.
#
# AMVER: the version of amanda we're working on.  This will become part of the
#     rpm name.  AMVER must line up with the version number mentioned in the
#     .spec file.
# PKG_DIR: Rpmbuild expects absolute paths, so we provide this var.  It also
#     allows you to build somewhere other than `pwd`.  You probably don't want
#     to use the system-wide location, as the script tries to blow these
#     directories away.
# 
# Other Hints:
# Not everyone will want to use the ./configure options we provide.  The
# easiest way to change them is by editing the .spec file.  This isn't so
# easy, unfortunately.  Look at the %build section, and the %define xxxx 
# statements immediately above it. good luck.

pkg_name=amanda
. packaging/common/build_functions.sh
. config/set_full_version

# Until we get package revisioning in community.
[ -f "PKG_REV" ] || echo "1" > PKG_REV

do_rpm_package() {
    gen_pkg_build_config $buildpkg_dir
    # take the spec/spec.src files and make a tarfile
    gen_pkg_environ
    [ -s rpmbuild/SOURCES/${PKG_NAME_VER}.tar.gz ] || {
            echo >&2 "missing rpmbuild/SOURCES/${PKG_NAME_VER}.tar.gz file version=$PKG_NAME_VER in ${PWD}"
            exit 1
          }
    do_package "$@"
}

set -e

do_rpm_package "amanda.spec"
