#!/bin/bash

buildtype=${1:-both}
shift

# set the var buildpkg_dir as well
. ./packaging/common/build_functions.sh
. ./packaging/common/set_zmanda_version
detect_package_vars

# . ./packaging/common/set_zmanda_version

export PKG_DIR=$(realpath .)

do_deb_package() {
    gen_pkg_build_config "$@"
    gen_pkg_environ
    do_package "${PKG_NAME_VER}"
}

set -e

case "$buildtype" in
   both)
        do_deb_package "$buildpkg_dir/server"
        do_deb_package "$buildpkg_dir/client"
        ;;

   server)
        do_deb_package "$buildpkg_dir/server"
        ;;

   client)
        do_deb_package "$buildpkg_dir/client"
        ;;

   *) echo "ERROR: cannot build combination of $buildtype" >&2; exit -1 ;;
esac

true
