#!/usr/bin/env bash

#
# VERSION: the identifier for the amanda determined from git
#	information.
# PKG_NAME_VER: the full version name of amanda we're working on.  This will
#	become part of the sun name.  {PKG_NAME_VER} gets substituted
#

buildtype=${1:-both}
shift

# set the var buildpkg_dir as well
. ./packaging/common/build_functions.sh
. ./packaging/common/set_zmanda_version

[ -d /opt/csw/gnu ] && [[ "$PATH" != */opt/csw/gnu* ]] && PATH=/opt/csw/gnu:${PATH}
[ -d /usr/sfw/bin ] && [[ "$PATH" != */usr/sfw/bin* ]] && PATH=/usr/sfw/bin:${PATH}
[ -d /usr/ccs/bin ] && [[ "$PATH" != */usr/ccs/bin* ]] && PATH=${PATH}:/usr/ccs/bin

export PATH
export PKG_DIR=$(realpath .)
mach=`uname -m`

do_sun_package() {
    gen_pkg_build_config "$@"
    gen_pkg_environ
    do_package "${PKG_NAME_VER}"
}

set -e

case "$buildtype" in
   both)
        do_sun_package "$buildpkg_dir/server"
        do_sun_package "$buildpkg_dir/client"
        ;;

   server)
        do_sun_package "$buildpkg_dir/server"
        ;;

   client)
        do_sun_package "$buildpkg_dir/client"
        ;;

   *) echo "ERROR: cannot build combination of $buildtype" >&2; exit -1 ;;
esac

true
