#!/usr/bin/env bash

# Buildpkg is designed to be used by both buildbot (to automate deb production)
# and by J Random User (to build a deb for kicks).
#
# VERSION: the identifier for the amanda determined from subversion
#	information.  
# PKG_NAME_VER: the full version name of amanda we're working on.  This will
#	become part of the deb name.  {PKG_NAME_VER} gets substituted into
#	various package files.  
#

buildtype=${1:-both}
shift

# set the var buildpkg_dir as well
. ./packaging/common_z/build_functions.sh
. ./packaging/common_z/set_zmanda_version

[ -d /opt/csw/gnu ] && [[ "$PATH" != */opt/csw/gnu* ]] && PATH=/opt/csw/gnu:${PATH}
[ -d /usr/sfw/bin ] && [[ "$PATH" != */usr/sfw/bin* ]] && PATH=/usr/sfw/bin:${PATH}
[ -d /usr/ccs/bin ] && [[ "$PATH" != */usr/ccs/bin* ]] && PATH=${PATH}:/usr/ccs/bin

export PATH
export PKG_DIR=$(realpath .)

mach=`uname -m`
# build only if not blocked by arch or directive
if [ "$buildtype" = "server" -o "$buildtype" = both ] && [ $mach = "x86_64" ]; then
    # debian must be cleared-and-created twice
    gen_pkg_build_config "$buildpkg_dir/server"
    gen_pkg_environ
    do_package "${PKG_NAME_VER}"
fi

if [ "$buildtype" = "client" -o "$buildtype" = both ]; then
    # debian must be cleared-and-created twice
    gen_pkg_build_config "$buildpkg_dir/client"
    gen_pkg_environ
    do_package "${PKG_NAME_VER}"
fi

exit 0
